# This is a CI workflow that runs on successful PR Merge into dev branch

name: CI Build

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request event for the dev branch
  # push:
  workflow_dispatch:
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      # Install NodeJS
      - name: setup node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Clean Install packages
        run: npm ci

      # Build library and project
      - name: Build AptColorPicker
        run: npm run build-lib-ci

      - name: Build App
        run: npm run build-ci

      - name: Test
        run: npm run test-ci
