# This is a CI workflow that runs on successful PR Merge into dev branch

name: CI BUILD

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request event for the dev branch
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it     
      - uses: actions/checkout@v2
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # Build library and project
      - name: Build
        run: npm ci

      - name: Test library and project
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
